<?php
/** @var \Daviz\Contact\Block\Attachment $block */
?>
<?php if ($block->getStatusLogin() == true) : ?>
<p style="font-size: 15px;">
    <b><?php echo __('Attachment'); ?></b>
    <?php echo __('(Upload any relevant file e.g. screenshot of website error)'); ?>
</p>
<p id="file_error" class="message-error error message" style="display:none;">
    <?php echo __('(File is too large)'); ?>
</p>
<p class="file">
    <?php echo __('(File must be less than 2MB and in any of these formats: .jpg, .png, .gif, .pdf, .docx)'); ?>
</p>
<input id="file-btn" accept=".pdf, .png, .jpg, .gif, .docx, .jpeg/*" name="document" type="file" value="">
<script type="text/javascript" xml="space">
require(['jquery'], function ($) {
    jQuery(document).ready(function($){
        let uploadField = document.getElementById("file-btn");
        uploadField.onchange = function() {
            if(this.files[0].size >= 2121829){
                $('#file_error').show();
                this.value = "";
            }else{
                $('#file_error').hide();
            };
        };
    });
});
</script>
<?php else : ?>
<p><?php echo __('Please register for file attachment '); ?></p>
<?php endif; ?>
